---

- name: Copy aws config
  ansible.builtin.copy:
    src: files/.aws/config
    dest: ~/.aws/config

- name: Copy aws credentials
  ansible.builtin.copy:
    src: files/.aws/credentials
    dest: ~/.aws/credentials

- name: Copy terraform cloud credentials
  ansible.builtin.copy:
    src: files/.terraformrc
    dest: ~/.terraformrc

- name: Copy certs
  ansible.builtin.copy:
    src: files/certs
    dest: ~/certs

- name: Copy .pypirc
  ansible.builtin.copy:
    src: files/.pypirc
    dest: ~/.pypirc

- name: Copy .zshrc
  ansible.builtin.copy:
    src: files/.zshrc
    dest: ~/.zshrc

- name: Copy .zprofile
  ansible.builtin.copy:
    src: files/.zprofile
    dest: ~/.zprofile

- name: Copy .zsh_history
  ansible.builtin.copy:
    src: files/.zsh_history
    dest: ~/.zsh_history

- name: Copy jl.zsh-theme
  ansible.builtin.copy:
    src: files/jl.zsh-theme
    dest: ~/.oh-my-zsh/themes/jl.zsh-theme

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: files/.gitconfig
    dest: ~/.gitconfig

- name: Copy vscode settings
  ansible.builtin.copy:
    src: files/vscode/settings.json
    dest: ~/Library/Application\ Support/Code/User/settings.json

