---

- name: Create aws dotfiles directory
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    mode: '0744'

- name: Copy aws config
  ansible.builtin.copy:
    src: .aws/config
    dest: ~/.aws/config

# - name: Copy aws credentials
#   ansible.builtin.copy:
#     src: .aws/credentials
#     dest: ~/.aws/credentials

- name: Create terraform dotfiles directory
  ansible.builtin.file:
    path: ~/.terraformrc
    state: directory
    mode: '0744'

# - name: Copy terraform cloud credentials
#   ansible.builtin.copy:
#     src: .terraformrc
#     dest: ~/.terraformrc

- name: Copy certs
  ansible.builtin.copy:
    src: certs
    dest: ~/certs

- name: Create pypirc dotfiles directory
  ansible.builtin.file:
    path: ~/.pypirc
    state: directory
    mode: '0744'

- name: Copy .pypirc
  ansible.builtin.copy:
    src: .pypirc
    dest: ~/.pypirc

- name: Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: ~/.zshrc

- name: Copy .zprofile
  ansible.builtin.copy:
    src: .zprofile
    dest: ~/.zprofile

- name: Copy .zsh_history
  ansible.builtin.copy:
    src: .zsh_history
    dest: ~/.zsh_history

- name: Copy jl.zsh-theme
  ansible.builtin.copy:
    src: jl.zsh-theme
    dest: ~/.oh-my-zsh/themes/jl.zsh-theme

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: .gitconfig
    dest: ~/.gitconfig

- name: Copy vscode settings
  ansible.builtin.copy:
    src: code/settings.json
    dest: ~/Library/Application\ Support/Code/User/settings.json

