---
- name: Homebrew update
  community.general.homebrew:
    update_homebrew: yes

- name: Homebrew packages install
  community.general.homebrew:
    name: '{{ item}}'
    state: '{{ item.state | default("present") }}'
  loop: '{{ homebrew_apps }}'

- name: Homebrew cask install
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: '{{ item.state | default("present") }}'
  loop: '{{ cask_apps }}'

- name: Install Logic Pro
  community.general.mas:
    id: "{{ item }}"
    state: present
  loop: '{{ mas_apps }}'

